spring.application.name=MoneyMap

spring.datasource.url=jdbc:postgresql://localhost:5432/MoneyMapDB
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=L54OZNDg9xvTuB+kGTxzS+8QgZ6X6mQ0eGiM9MkYKPY=